config/routes.rb
Rails.application.routes.draw do
  # Defined routes for user profiles
  resources :user_profiles, only: [:show, :edit, :update, :destroy]

  # Defined application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defined the root path route ("/")
  root to: "home#index"

  # Devise routes for user authentication
  devise_for :users

  #In an attempt to consolidate the API routes
  # Defined API routes within the 'api/v1' namespace
  namespace :api do
    namespace :v1 do
      # Defined API routes for job listings and job details
      resources :job_listings, :job_details, except: [:edit, :new]

      # Defined a single route for job search and user search
      get '/search', to: 'job_search#index', on: :collection
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_listing.rb
class JobListing < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
            # Include default devise modules.
            devise :database_authenticatable, :registerable,
                    :recoverable, :rememberable, :trackable, :validatable,
                    :confirmable, :omniauthable
            include DeviseTokenAuth::Concerns::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Adding the association with UserProfile
  has_one :user_profile, dependent: :destroy
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/api/v1/job_details_controller.rb
class Api::V1::JobDetailsController < ApplicationController
end

app/controllers/api/v1/job_listings_controller.rb
class Api::V1::JobListingsController < ApplicationController
end

app/controllers/api/v1/job_search_controller.rb
module Api
  module V1
    class JobSearchController < ApplicationController
      def index
        # Define search parameters from query parameters
        keywords = params[:keywords]
        location = params[:location]

        # Initialize a base query
        @results = JobListing.all

        # Apply filters based on query parameters
        if keywords.present?
          # Perform a case-insensitive search in title and description
          @results = @results.where("lower(title) LIKE ? OR lower(description) LIKE ?", "%#{keywords.downcase}%", "%#{keywords.downcase}%")
        end

        if location.present?
          @results = @results.where("lower(location) LIKE ?", "%#{location.downcase}%")
        end

        # You can add more filtering based on other query parameters here

        render json: @results
      end
    end
  end
end

app/controllers/api/v1/user_search_controller.rb
module Api
  module V1
    class UserSearchController < ApplicationController
      def index
        name = params[:name]

        # Perform user search based on the name parameter
        @results = User.where("lower(name) LIKE ?", "%#{name.downcase}%")

        render json: @results
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        include DeviseTokenAuth::Concerns::SetUserByToken
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: %i[ show edit update destroy ]

  # GET /user_profiles or /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1 or /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles or /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to user_profile_url(@user_profile), notice: "User profile was successfully created." }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1 or /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to user_profile_url(@user_profile), notice: "User profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1 or /user_profiles/1.json
  def destroy
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: "User profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_profile_params
      params.require(:user_profile).permit(:name, :bio, :user_id)
    end
end

app/helpers/api/v1/job_details_helper.rb
module Api::V1::JobDetailsHelper
end

app/helpers/api/v1/job_listings_helper.rb
module Api::V1::JobListingsHelper
end

app/helpers/api/v1/job_search_helper.rb
module Api::V1::JobSearchHelper
end

app/helpers/api/v1/user_search_helper.rb
module Api::V1::UserSearchHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobQuest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/user_profiles/_form.html.erb
<%= form_with(model: user_profile) do |form| %>
  <% if user_profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
        <% user_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_profiles/_user_profile.html.erb
<div id="<%= dom_id user_profile %>">
  <p>
    <strong>Name:</strong>
    <%= user_profile.name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= user_profile.bio %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user_profile.user_id %>
  </p>

</div>

app/views/user_profiles/edit.html.erb
<h1>Editing user profile</h1>

<%= render "form", user_profile: @user_profile %>

<br>

<div>
  <%= link_to "Show this user profile", @user_profile %> |
  <%= link_to "Back to user profiles", user_profiles_path %>
</div>

app/views/user_profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User profiles</h1>

<div id="user_profiles">
  <% @user_profiles.each do |user_profile| %>
    <%= render user_profile %>
    <p>
      <%= link_to "Show this user profile", user_profile %>
    </p>
  <% end %>
</div>

<%= link_to "New user profile", new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user profile</h1>

<%= render "form", user_profile: @user_profile %>

<br>

<div>
  <%= link_to "Back to user profiles", user_profiles_path %>
</div>

app/views/user_profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_profile %>

<div>
  <%= link_to "Edit this user profile", edit_user_profile_path(@user_profile) %> |
  <%= link_to "Back to user profiles", user_profiles_path %>

  <%= button_to "Destroy this user profile", @user_profile, method: :delete %>
</div>